### ISSUE TITLE
Cannot instantiate module

### ISSUE THREAD

**Issue by andyaem** [maros/Zway-SecurityZone#1]
Hello Maros,

maybe I'm to stupid, but when trying to instantiate SecurityZone (Apps - Local Apps - Add App) it throws an error message as follows:
"Cannot instantiate module: SecurityZone: TypeError: undefined is not a function".

/var/log/z-way-server.log tells:

[2016-01-29 22:53:23.358] [I] [core] Notification: error (core): Cannot instantiate module: SecurityZone: TypeError: undefined is not a function
[2016-01-29 22:53:23.388] [I] [core] TypeError: undefined is not a function
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:325:24)
    at AutomationController.createInstance (automation/classes/AutomationController.js:627:14)
    at ZAutomationAPIWebRequest._.extend.createInstance (automation/ZAutomationAPIProvider.js:1054:40)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:258:41)
    at automation/WebserverRequestRouter.js:32:35
    at WebServer.document_root (automation/Webserver.js:29:11)

BaseModule is installed and instanciated. Same result with SecurityZone V 1.05 as well as V1.06.

**Comment by maros** [comment]
Usually this error occurs if module.json cannot be loaded. Please make sure that the file is readable by the user running the z-way engine (permissions. folder name without "Zway-" prefix, ...)
